meta_product_name: "Up in the Air"
meta_title: "Up in the Air - Not endorsed by George Clooney"
meta_description: "Arrange trips with your friends, no matter where in the world they live."
meta_image: "london.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
